// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteKeyworks.Data;

#nullable disable

namespace TesteKeyworks.Migrations
{
    [DbContext(typeof(TesteKeyworksContext))]
    [Migration("20231221190241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteKeyworks.Models.Filme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioAvaliacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Filme");
                });

            modelBuilder.Entity("TesteKeyworks.Models.FilmesStreamings", b =>
                {
                    b.Property<Guid>("StreamingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilmeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StreamingId", "FilmeId");

                    b.HasIndex("FilmeId");

                    b.ToTable("FilmesStreamings");
                });

            modelBuilder.Entity("TesteKeyworks.Models.Streaming", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Streaming");
                });

            modelBuilder.Entity("TesteKeyworks.Models.FilmesStreamings", b =>
                {
                    b.HasOne("TesteKeyworks.Models.Filme", "Filme")
                        .WithMany("FilmesStreamings")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteKeyworks.Models.Streaming", "Streaming")
                        .WithMany("FilmesStreamings")
                        .HasForeignKey("StreamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Streaming");
                });

            modelBuilder.Entity("TesteKeyworks.Models.Filme", b =>
                {
                    b.Navigation("FilmesStreamings");
                });

            modelBuilder.Entity("TesteKeyworks.Models.Streaming", b =>
                {
                    b.Navigation("FilmesStreamings");
                });
#pragma warning restore 612, 618
        }
    }
}
